default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.7.0"
    hooks:
      - id: autopep8
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: "v1.3.5"
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: "v0.6.13"
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: https://github.com/janosh/format-ipy-cells
    rev: "v0.1.10"
    hooks:
      - id: format-ipy-cells
  - repo: https://gitlab.com/iamlikeme/nbhooks
    rev: "1.0.0"
    hooks:
      - id: nb-ensure-clean
        args: [--meta, ExecuteTime] # Optional blacklist of metadata keys (you can use regex)
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.17.0"
    hooks:
      - id: gitlint
