#!/usr/bin/env bash

GIT_ROOT_PATH="$(git rev-parse --show-toplevel)"
PRE_COMMIT_DIR="${HOME}/.gittemplate/pre-commit"
COMMIT_MSG_LOCAL_CONFIG="${GIT_ROOT_PATH}/.commit-msg-config.yaml"
COMMIT_MSG_GLOBAL_CONFIG="${PRE_COMMIT_DIR}/.commit-msg-config.yaml"

if [ ! -f "$COMMIT_MSG_LOCAL_CONFIG" ]; then
    ARGS=(hook-impl --config=${COMMIT_MSG_GLOBAL_CONFIG} --hook-type=commit-msg --color=always)
else
    ARGS=(hook-impl --config=${COMMIT_MSG_LOCAL_CONFIG} --hook-type=commit-msg --color=always)
fi

CURRENT_PATH="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$CURRENT_PATH" -- "$@")
if command -v pre-commit >/dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to install the package?' 1>&2
    exit 1
fi