#!/usr/bin/env bash

GIT_ROOT_PATH="$(git rev-parse --show-toplevel)"
PRE_COMMIT_DIR="${HOME}/.gittemplate/pre-commit"
PRE_COMMIT_LOCAL_CONFIG="${GIT_ROOT_PATH}/.pre-commit-config.yaml"
PRE_COMMIT_GLOBAL_CONFIG="${PRE_COMMIT_DIR}/.pre-commit-config.yaml"

if [ ! -f "$LOCAL_CONFIG" ]; then
    ARGS=(hook-impl --config=${PRE_COMMIT_GLOBAL_CONFIG} --hook-type=pre-commit --color=always)
else
    ARGS=(hook-impl --config=${PRE_COMMIT_LOCAL_CONFIG} --hook-type=pre-commit --color=always)
fi

CURRENT_PATH="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$CURRENT_PATH" -- "$@")
if command -v pre-commit >/dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to install the package?' 1>&2
    exit 1
fi
