#!/usr/bin/env bash

HERE="$(cd "$(dirname "$0")" && pwd)"
LOCAL_CONFIG="${HERE}/.pre-commit-config.yaml"

if [ ! -f "$LOCAL_CONFIG" ]; then
    ARGS=(hook-impl --config=${HOME}/.pre-commit-config.yaml --hook-type=pre-commit)
else
    ARGS=(hook-impl --config=${LOCAL_CONFIG} --hook-type=pre-commit)
fi

ARGS+=(--hook-dir "$HERE" -- "$@")
if command -v pre-commit >/dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to install the package?' 1>&2
    exit 1
fi
