default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.17.0"
    hooks:
      - id: gitlint
        args: [--config, /Users/mohabouje/.gitlint, --msg-filename]
